services:
  app:
    build: .
    image: bkaindl/whatsmail:latest
    container_name: whatsmail
    restart: unless-stopped
    ports:
      - 666:3000
    networks:
      - web

networks:
  web:
    name: web
    external: true
